[package]
name = "oncouch"
version = "0.1.0"
authors = ["Thiago Diniz da Silveira <thiagods.ti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strsim = "0.10.0"
regex = "1.3.7"
prettytable-rs = "^0.8"
